// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyWNEuQr7yTDHHNdpivAEfBHmCtQbVS3Y',
    appId: '1:90787169842:web:c4b67d7aa53a90a67f5e2b',
    messagingSenderId: '90787169842',
    projectId: 'sinaufirebase-87fee',
    authDomain: 'sinaufirebase-87fee.firebaseapp.com',
    storageBucket: 'sinaufirebase-87fee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAHgBTfgSoHLtr8dP4961AIVzPd8I2rRg',
    appId: '1:90787169842:android:a30184a825c361fc7f5e2b',
    messagingSenderId: '90787169842',
    projectId: 'sinaufirebase-87fee',
    storageBucket: 'sinaufirebase-87fee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuVd-kpf4xTvWWuYNnqMpMCqHAjB_s_QM',
    appId: '1:90787169842:ios:987da7093c6660fa7f5e2b',
    messagingSenderId: '90787169842',
    projectId: 'sinaufirebase-87fee',
    storageBucket: 'sinaufirebase-87fee.firebasestorage.app',
    iosBundleId: 'com.example.sinauFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuVd-kpf4xTvWWuYNnqMpMCqHAjB_s_QM',
    appId: '1:90787169842:ios:987da7093c6660fa7f5e2b',
    messagingSenderId: '90787169842',
    projectId: 'sinaufirebase-87fee',
    storageBucket: 'sinaufirebase-87fee.firebasestorage.app',
    iosBundleId: 'com.example.sinauFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyWNEuQr7yTDHHNdpivAEfBHmCtQbVS3Y',
    appId: '1:90787169842:web:ea20674625dc37747f5e2b',
    messagingSenderId: '90787169842',
    projectId: 'sinaufirebase-87fee',
    authDomain: 'sinaufirebase-87fee.firebaseapp.com',
    storageBucket: 'sinaufirebase-87fee.firebasestorage.app',
  );
}
