// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1r6bc49kvjUi_ctoaGb8vuTal-Z6tWO8',
    appId: '1:811576956737:web:828cb2bf8d446da295b3c0',
    messagingSenderId: '811576956737',
    projectId: 'journalist-eb50f',
    authDomain: 'journalist-eb50f.firebaseapp.com',
    storageBucket: 'journalist-eb50f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwF8EDaBI1jqwIpZNN_hgqz9mq55NGGQ8',
    appId: '1:811576956737:android:36f11ae09adcc47195b3c0',
    messagingSenderId: '811576956737',
    projectId: 'journalist-eb50f',
    storageBucket: 'journalist-eb50f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi-KfOqFnYzJfDjotHMSD4kWvhlE82ots',
    appId: '1:811576956737:ios:a26a3f8e1339ce3a95b3c0',
    messagingSenderId: '811576956737',
    projectId: 'journalist-eb50f',
    storageBucket: 'journalist-eb50f.firebasestorage.app',
    iosBundleId: 'com.example.newsJournalist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi-KfOqFnYzJfDjotHMSD4kWvhlE82ots',
    appId: '1:811576956737:ios:a26a3f8e1339ce3a95b3c0',
    messagingSenderId: '811576956737',
    projectId: 'journalist-eb50f',
    storageBucket: 'journalist-eb50f.firebasestorage.app',
    iosBundleId: 'com.example.newsJournalist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1r6bc49kvjUi_ctoaGb8vuTal-Z6tWO8',
    appId: '1:811576956737:web:044031f12dc9579895b3c0',
    messagingSenderId: '811576956737',
    projectId: 'journalist-eb50f',
    authDomain: 'journalist-eb50f.firebaseapp.com',
    storageBucket: 'journalist-eb50f.firebasestorage.app',
  );
}
