name: sinau_firebase
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  image_picker: ^1.1.2 # Pastikan ini ada jika Anda berencana menggunakannya
  firebase_storage: ^12.4.6 # Pastikan ini ada jika Anda berencana menggunakannya
  flutter_native_splash: ^2.4.6 # Paketnya sudah benar di sini

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # flutter_launcher_icons akan dikonfigurasi di level root juga jika Anda menggunakannya

# Konfigurasi flutter_native_splash seharusnya di sini, di level root
flutter_native_splash:
  color: "#FFFFFF" # Contoh: Putih
  # Atau gunakan background_image untuk gambar latar (misalnya gradient).
  # background_image: "assets/images/splash_background.png"

  # Parameter opsional:
  # image digunakan untuk menampilkan logo di tengah splash screen.
  # Pastikan path-nya benar dan gambar sudah ada di folder assets.
  image: assets/images/logo.png # Ganti dengan path logo Anda

  # Branding (opsional, muncul di bagian bawah untuk Android < 12)
  # branding: assets/images/branding_logo.png
  # branding_mode: bottom

  # Pengaturan untuk mode gelap (opsional)
  color_dark: "#ffffff"
  # image_dark: assets/images/logo_dark.png # Jika punya logo versi gelap

  # Pengaturan spesifik untuk Android 12+
  android_12:
    image: assets/images/logo.png # Icon untuk Android 12+
    color: "#FFFFFF" # Warna latar Android 12+
    # icon_background_color: "#111111" # Warna latar belakang ikon (jika ikon tidak memenuhi area)
    # branding: assets/images/android12_branding.png

  # Anda bisa menonaktifkan splash untuk platform tertentu
  # android: false
  # ios: false
  # web: false

# Bagian flutter untuk assets, fonts, dll.
flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png # Pastikan ini sudah ada dan mendaftarkan folder logo Anda
    # - assets/images/logo.png # Atau daftarkan secara spesifik jika hanya satu file
